services:
  - type: web
    name: render-test-app-laravel
    plan: free
    runtime: docker 
    envVars:
      - key: APP_KEY
        sync: false 
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: render-test-app-laravel
          property: host
    postDeployCommands:
      - "php artisan migrate --force"